# Generated by Django 4.1 on 2023-09-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Farm', models.CharField(max_length=250, verbose_name='Farm')),
                ('Field', models.CharField(max_length=250, verbose_name='Field')),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('State', models.CharField(max_length=250, verbose_name='State')),
                ('Data_time', models.DateTimeField(auto_now_add=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='assets/images', verbose_name='image')),
                ('hashing_path', models.CharField(max_length=250, verbose_name='Hashing Path')),
                ('kat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.users')),
            ],
        ),
    ]
