# Generated by Django 4.1 on 2023-09-04 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250, verbose_name='Adı')),
                ('father_name', models.CharField(max_length=250, verbose_name='Ata adı')),
                ('last_name', models.CharField(max_length=250, verbose_name='Soyadı')),
                ('city', models.CharField(max_length=250, verbose_name='Ülke ve ya Şehir')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='assets/images', verbose_name='image')),
                ('phone', models.CharField(max_length=250, verbose_name='phone')),
                ('departments', models.CharField(max_length=250, verbose_name='departments')),
                ('gender', models.CharField(max_length=250, verbose_name='cinsi')),
                ('bio', models.CharField(max_length=2500, verbose_name='bio')),
                ('birthday', models.DateField(verbose_name='Doğum günü')),
                ('address', models.CharField(max_length=2500, verbose_name='Ünvan')),
                ('website', models.URLField(default=None, max_length=250, verbose_name='Veb sayt')),
                ('kat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
